#!/bin/bash
touch \
    ./src/tros/performance_test_fixture/COLCON_IGNORE \
    ./src/tros/rviz/COLCON_IGNORE \
    ./src/tools/benchmark/performance_test_ros1_msgs/COLCON_IGNORE \
    ./src/tools/benchmark/performance_test_ros1_publisher/COLCON_IGNORE \
    ./src/ros/ros_tutorials/COLCON_IGNORE \
    ./src/tros/ros1_bridge/COLCON_IGNORE \
    ./src/eProsima/compatibility/COLCON_IGNORE \
    ./src/box/ros-navigation/navigation2/nav2_system_tests/COLCON_IGNORE \
    ./src/box/ros-navigation/navigation2/nav2_rviz_plugins/COLCON_IGNORE \
    ./src/box/ros-navigation/navigation2/smac_planner/COLCON_IGNORE \
    ./src/box/hobot_sensors/image_subscribe_example/COLCON_IGNORE \
    ./src/box/hobot_sensors/mipi_cam/COLCON_IGNORE \
    ./src/box/hobot_sensors/rgbd_sensor/COLCON_IGNORE \
    ./src/box/hobot_hdmi/COLCON_IGNORE \
    ./src/box/hobot_audio/COLCON_IGNORE \
    ./src/box/hobot_interactions/COLCON_IGNORE \
    ./src/box/hobot_slam/COLCON_IGNORE \
    ./src/box/hobot_perception/mot/COLCON_IGNORE \
    ./src/box/hobot_perception/hand_gesture_detection/COLCON_IGNORE \
    ./src/box/hobot_perception/hand_lmk_detection/COLCON_IGNORE \
    ./src/box/hobot_perception/hobot_falldown_detection/COLCON_IGNORE \
    ./src/box/hobot_trigger/COLCON_IGNORE \
    ./src/app/xr_robot/COLCON_IGNORE \
    ./src/app/line_follower/COLCON_IGNORE \
    ./src/tools/benchmark/COLCON_IGNORE \
    ./src/box/ros-navigation/COLCON_IGNORE \
    ./src/box/hobot_sensors/imu_sensor/COLCON_IGNORE
