#!/bin/bash

#dpkg -s hhp  > /dev/null 2>&1
#if [$? -eq 0];then
#	sudo apt remove hhp
#fi

sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
if [ -e "/sys/class/socinfo/soc_uid" ]; then
	sudo hhp_verify
fi
